from .wrappers import DueDiligenceProfileWrapper
from datetime import datetime

due_diligence_db = [
      DueDiligenceProfileWrapper(
        id=1,
        name="Tech Innovators Inc.",
        url="https://www.techinnovators.com",
        email="info@techinnovators.com",
        founded=1980,
        founder="James Smith",
        address={"street": "500 Grand Avenue", "city": "1000 Brussels"},
        country="United States",
        Last_revision="29 Sept 2024",
        risk_level=4,
        status="Passed",
        description="Tech Innovators Inc. specializes in delivering advanced software solutions across multiple industries.",
        key_individuals={"CEO": "John Doe", "CTO": "Susan Klein", "COO": "Michael Johnson"},
        security_risk={"risk type": "on sanctions list", "details": "Business dealings with Eastern Europe."},
        financial_risk={"risk type": "low liquidity", "details": "High investment in R&D leading to liquidity issues."},
        operational_risk={"risk type": "project in Russia", "details": "Geopolitical climate impacting projects."},
        key_relationships={"key relationships": "Russia, China, Germany", "details": "Strategic partnerships for AI and cloud."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=2,
        name="Green Energy Ltd.",
        url="https://www.greenenergy.com",
        email="info@greenenergy.com",
        founded=2005,
        founder="Anna Braun",
        address={"street": "123 Solar Road", "city": "Berlin"},
        country="Germany",
        Last_revision="05 Dec 2023",
        risk_level=5,
        status="Failed",
        description="Green Energy Ltd. is a renewable energy leader specializing in solar and wind energy solutions.",
        key_individuals={"CEO": "Anna Braun", "COO": "Jürgen Schmidt"},
        security_risk={"risk type": "environmental compliance", "details": "Facing fines for improper disposal of materials."},
        financial_risk={"risk type": "high debt", "details": "Heavy investments in new technology have resulted in high debt."},
        operational_risk={"risk type": "supply chain disruption", "details": "Delays in wind turbine production."},
        key_relationships={"key relationships": "China, Spain", "details": "Solar technology partners in these regions."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=3,
        name="Auto Manufacturing Co.",
        url="https://www.automfg.com",
        email="info@automfg.com",
        founded=1965,
        founder="Hideo Nakamura",
        address={"street": "777 Industrial Parkway", "city": "Tokyo"},
        country="Japan",
        Last_revision="10 Feb 2024",
        risk_level=4,
        status="Failed",
        description="Auto Manufacturing Co. is a pioneer in electric vehicles, producing a range of automobiles globally.",
        key_individuals={"CEO": "Hideo Nakamura", "CTO": "Yuki Tanaka", "COO": "Kenji Sato"},
        security_risk={"risk type": "product recalls", "details": "Frequent vehicle recalls impacting reputation."},
        financial_risk={"risk type": "currency fluctuations", "details": "The strong yen has negatively impacted profitability."},
        operational_risk={"risk type": "production delays", "details": "Supply chain issues are affecting the launch of new models."},
        key_relationships={"key relationships": "Germany, South Korea", "details": "Strategic partnerships with parts suppliers."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=4,
        name="Healthcare Solutions LLC",
        url="https://www.healthcaresolutions.com",
        email="info@healthcaresolutions.com",
        founded=1998,
        founder="Sarah Walker",
        address={"street": "22 Medtech Blvd", "city": "London"},
        country="United Kingdom",
        Last_revision="20 Nov 2023",
        risk_level=3,
        status="Failed",
        description="Healthcare Solutions LLC develops cutting-edge medical devices for surgical and diagnostic use.",
        key_individuals={"CEO": "Sarah Walker", "CTO": "Tom Hudson"},
        security_risk={"risk type": "data breaches", "details": "Recent breaches of patient data."},
        financial_risk={"risk type": "slowing sales", "details": "Decreased demand for medical devices."},
        operational_risk={"risk type": "regulatory changes", "details": "Upcoming changes in medical device regulations."},
        key_relationships={"key relationships": "USA, Germany", "details": "Collaboration with top hospitals and universities."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=5,
        name="Financial Services Group",
        url="https://www.financialservices.com",
        email="info@financialservices.com",
        founded=1970,
        founder="Robert Davis",
        address={"street": "15 Wealth Avenue", "city": "Toronto"},
        country="Canada",
        Last_revision="01 Mar 2024",
        risk_level=2,
        status="Failed",
        description="Financial Services Group provides investment banking and wealth management services worldwide.",
        key_individuals={"CEO": "Robert Davis", "CFO": "Linda Graham"},
        security_risk={"risk type": "fraudulent activity", "details": "Investigations into insider trading practices."},
        financial_risk={"risk type": "market volatility", "details": "The company has been exposed to volatile stock markets."},
        operational_risk={"risk type": "regulatory compliance", "details": "Facing increased scrutiny from regulators."},
        key_relationships={"key relationships": "USA, UK", "details": "Strong partnerships with leading global banks."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=6,
        name="Retail Giants PLC",
        url="https://www.retailgiants.com",
        email="info@retailgiants.com",
        founded=1985,
        founder="Mary Brown",
        address={"street": "200 Commerce Street", "city": "Sydney"},
        country="Australia",
        Last_revision="15 Oct 2023",
        risk_level=1,
        status="Failed",
        description="Retail Giants PLC is a major player in e-commerce, offering a wide variety of consumer goods.",
        key_individuals={"CEO": "Mary Brown", "COO": "James Wilson"},
        security_risk={"risk type": "cybersecurity threats", "details": "Recent hacking attempts on the e-commerce platform."},
        financial_risk={"risk type": "increased competition", "details": "Rising competition from new e-commerce platforms."},
        operational_risk={"risk type": "logistics issues", "details": "Shipping delays during peak seasons."},
        key_relationships={"key relationships": "China, USA", "details": "Partnerships with leading consumer goods manufacturers."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=7,
        name="Aerospace Dynamics Corp.",
        url="https://www.aerospacedynamics.com",
        email="info@aerospacedynamics.com",
        founded=1995,
        founder="Pierre Dubois",
        address={"street": "120 Aviation Lane", "city": "Paris"},
        country="France",
        Last_revision="25 Jan 2024",
        risk_level=4,
        status="Failed",
        description="Aerospace Dynamics Corp. is a leading manufacturer of commercial and defense aircraft components.",
        key_individuals={"CEO": "Pierre Dubois", "COO": "Jacques Lefevre"},
        security_risk={"risk type": "contract disputes", "details": "Delays in defense contracts with governments."},
        financial_risk={"risk type": "capital constraints", "details": "Recent expansions have stretched financial resources."},
        operational_risk={"risk type": "quality control", "details": "Concerns over defects in aircraft parts."},
        key_relationships={"key relationships": "USA, UK", "details": "Supplies parts to leading aerospace manufacturers."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=8,
        name="Pharma Innovations Ltd.",
        url="https://www.pharmainnovations.com",
        email="info@pharmainnovations.com",
        founded=1987,
        founder="Hans Müller",
        address={"street": "9 Pharma Street", "city": "Zurich"},
        country="Switzerland",
        Last_revision="20 Feb 2024",
        risk_level=5,
        status="Passed",
        description="Pharma Innovations Ltd. focuses on pharmaceutical research, manufacturing both prescription and over-the-counter drugs.",
        key_individuals={"CEO": "Hans Müller", "CSO": "Ingrid Schneider"},
        security_risk={"risk type": "drug recalls", "details": "Recent recalls due to contamination issues."},
        financial_risk={"risk type": "patent expirations", "details": "Several key drug patents are expiring, impacting revenue."},
        operational_risk={"risk type": "clinical trial delays", "details": "Delays in clinical trials for new drug releases."},
        key_relationships={"key relationships": "USA, China", "details": "Strategic partnerships in pharmaceutical R&D."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=9,
        name="AeroTech Engineering Inc.",
        url="https://www.aerotecheng.com",
        email="info@aerotecheng.com",
        founded=1990,
        founder="David Thompson",
        address={"street": "33 Jet Drive", "city": "Seattle"},
        country="United States",
        Last_revision="05 Jan 2024",
        risk_level=4,
        status="Passed",
        description="AeroTech Engineering Inc. specializes in the production of jet engines and aviation electronics for commercial and defense sectors.",
        key_individuals={"CEO": "David Thompson", "COO": "Karen Lee"},
        security_risk={"risk type": "intellectual property theft", "details": "Recent cases of IP theft in aviation electronics."},
        financial_risk={"risk type": "cash flow issues", "details": "The company faces cash flow problems due to large project delays."},
        operational_risk={"risk type": "supply chain bottlenecks", "details": "Delays in obtaining key parts from international suppliers."},
        key_relationships={"key relationships": "Japan, UK", "details": "Collaboration with aerospace companies in these regions."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=10,
        name="EcoGreen Energy Solutions",
        url="https://www.ecogreenenergy.com",
        email="contact@ecogreenenergy.com",
        founded=2010,
        founder="Sven Müller",
        address={"street": "500 Renewable Drive", "city": "Munich"},
        country="Germany",
        Last_revision="15 Nov 2023",
        risk_level=2,
        status="Failed",
        description="EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.EcoGreen Energy Solutions is a renewable energy company focused on solar and wind power solutions.",
        key_individuals={"CEO": "Sven Müller", "CTO": "Claudia Schneider"},
        security_risk={"risk type": "environmental regulations", "details": "Meeting strict environmental standards."},
        financial_risk={"risk type": "low revenue growth", "details": "Slow growth in key markets."},
        operational_risk={"risk type": "supply chain disruptions", "details": "Global supply chain issues affecting production."},
        key_relationships={"key relationships": "Spain, USA", "details": "Strong partnerships in renewable energy technology."},
        due_diligence_timestamp=datetime.now(),
    ),
    DueDiligenceProfileWrapper(
        id=11,
        name="Global Financial Investments",
        url="https://www.globalfininv.com",
        email="info@globalfininv.com",
        founded=1985,
        founder="Emma Brown",
        address={"street": "25 Finance Street", "city": "London"},
        country="United Kingdom",
        Last_revision="30 Dec 2023",
        risk_level=3,
        status="Passed",
        description="Global Financial Investments provides comprehensive wealth management and investment services globally.",
        key_individuals={"CEO": "Emma Brown", "CFO": "Richard Hill"},
        security_risk={"risk type": "regulatory issues", "details": "Facing potential regulatory scrutiny in capital markets."},
        financial_risk={"risk type": "market volatility", "details": "Fluctuations in global markets impacting profitability."},
        operational_risk={"risk type": "staff turnover", "details": "High staff turnover in key departments."},
        key_relationships={"key relationships": "USA, Hong Kong", "details": "Strong relationships with key financial institutions."},
        due_diligence_timestamp=datetime.now(),
    ),

]

