
services:
  due_diligence:
    container_name: DueDiligence_OpenAi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - redis      
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

# volumes:
#   redis-data:

