name: procurement-sourcing

services:
  procurement-explorer:
    container_name: procurement-explorer
    restart: unless-stopped
    build:
      context: ./backend/procurement-explorer
      dockerfile: Dockerfile
    depends_on:
      - db-postgres
    ports:
      - "${EXPLORER_PORT}:8000"
    environment:
      - PYTHONUNBUFFERED=1 # Ensures immediate printing
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGREST_INITIAL_LOADING_DATA=${POSTGREST_INITIAL_LOADING_DATA}
      - DD_INITIAL_LOADING_DATA=${DD_INITIAL_LOADING_DATA}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - OLLAMA_URL=${OLLAMA_URL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TYPE=${LLM_TYPE}
      - CRAWLER_URL=${CRAWLER_URL}
      - CRAWLER_PORT=${CRAWLER_PORT}
      - DD_URL=${DD_URL}
      - DD_PORT=${DD_PORT}

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - procurement-explorer
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_API_PORT: ${VITE_API_PORT}

  ollama:
    container_name: ollama
    build:
      context: ollama
      dockerfile: Dockerfile
    depends_on:
      - db-postgres
    ports:
      - "${OLLAMA_PORT}:11434"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  crawler:
    build:
      context: ./backend/company-profile-crawler
      dockerfile: docker/Dockerfile
    container_name: ps-crawler
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    depends_on:
      - db-postgres
    working_dir: /app/go/scraper
    entrypoint: "go run ./"

  crawler-api:
    container_name: ps-crawler-api
    build:
      context: ./backend/company-profile-crawler
      dockerfile: docker/Dockerfile-api
    restart: unless-stopped
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${CRAWLER_PORT}:80"
    depends_on:
      - db-postgres
    working_dir: /app/go/api
    entrypoint: "go run ./"

  db-postgres:
    image: postgres:14 # https://hub.docker.com/_/postgres
    container_name: ps-db-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./backend/database/:/docker-entrypoint-initdb.d/
    #command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    command: ["postgres"]

volumes:
  postgres-db-data:
    driver: local
