export default {
  primary: '#014289',
  disabled: '#a8a9ab',
  secondary: '#352AA3',
  primaryHover: '#003064',
  secondaryHover: '#F3F3F8',
  white: '#FFFFFF',
  statusPrimary: '#F1E6FF',
  statusSecondary: '#DAE5FC',
  statusTernary: '#e7e7e7',
  statusQuaternary: '#F7EEDF',
  statusQuinary: '#e0f6e6',
  textPrimary: '#292C3D',
  textSecondary: '#292C3D',
  backgroundCard: '#FFFFFF',
  backgroundPrimary: '#f6f6f8',
  backgroundSecondary: '#E0E3FF',
  stroke: '#EBEBF1',
  radiusSmall: '4px',
  radiusMedium: '8px',
};
